    // glBegin(GL_TRIANGLES);
    // glVertex3f(eye[0], eye[1], eye[2]);
    // // glVertex3f();
    // glVertex3f(-w, h, -my_near);
    // glEnd();
    // glBegin(GL_TRIANGLES);
    // glVertex3f(eye[0], eye[1], eye[2]);
    // glVertex3f(w, h, -my_near);
    // glVertex3f(-w, h, -my_near);
    // glEnd();
    // glBegin(GL_TRIANGLES);
    // glVertex3f(eye[0], eye[1], eye[2]);
    // glVertex3f(w, -h, -my_near);
    // glVertex3f(-w, -h, -my_near);
    // glEnd();
    // glBegin(GL_QUADS);
    // glVertex3f(w, h, -my_near);
    // glVertex3f(w, -h, -my_near);
    // glVertex3f(-w, -h, -my_near);
    // glVertex3f(-w, h, -my_near);
    // glEnd();